export const CATS = [
    {
        id: 0,
        name: "Cat1",
        image: require("../components/images/catToAdopt1.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 1,
        name: "Cat2",
        image: require("../components/images/catToAdopt2.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 2,
        name: "Cat3",
        image: require("../components/images/catToAdopt3.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 3,
        name: "Cat4",
        image: require("../components/images/catToAdopt4.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 4,
        name: "Cat5",
        image: require("../components/images/catToAdopt5.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 5,
        name: "Cat6",
        image: require("../components/images/catToAdopt6.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 6,
        name: "Cat7",
        image: require("../components/images/catToAdopt7.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 7,
        name: "Cat8",
        image: require("../components/images/catToAdopt8.jpg"),
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
];
