export const DOGS = [
    {
        id: 0,
        name: "Dog1",
        breed: "Breed1",
        image: require("../components/images/dogToAdopt1.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id: 1,
        name: "Dog2",
        breed: "Breed2",
        image: require("../components/images/dogToAdopt2.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 2,
        name: "Dog3",
        breed: "Breed3",
        image: require("../components/images/dogToAdopt3.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 3,
        name: "Dog4",
        breed: "Breed4",
        image: require("../components/images/dogToAdopt4.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 4,
        name: "Dog5",
        breed: "Breed5",
        image: require("../components/images/dogToAdopt5.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id: 5,
        name: "Dog6",
        breed: "Breed6",
        image: require("../components/images/dogToAdopt6.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 6,
        name: "Dog7",
        breed: "Breed7",
        image: require("../components/images/dogToAdopt7.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id:7,
        name: "Dog8",
        breed: "Breed8",
        image: require("../components/images/dogToAdopt8.jpg"),
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
];
